version: '3.8'

services:
  user-service:
    build:
        context: .
        dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env


      